---
- name: repox database
  mysql_db:
    name: "{{ repox_mariadb_database }}"
    state: present
- name: repox user for database
  mysql_user:
    name: "{{ repox_mariadb_username }}"
    host: "{{ repox_mariadb_host }}"
    password: "{{ repox_mariadb_password }}"
    priv: "{{ repox_mariadb_database }}.*:{{ repox_mariadb_privileges }}"
    state: present
