---
- name: install the repox war into tomcat
  copy:
    src: "{{ repox_path_source }}/gui/target/repox.war"
    dest: "{{ repox_path_tomcat }}/webapps/"
- name: replace default admin user
  template:
    src: users.xml.j2
    dest: "{{ repox_path_data }}/repoxData/configuration/users.xml"
