---
- include: yum.yml
  sudo: yes
- include: services.yml
  sudo: yes
- include: database.yml
  sudo: yes
- include: source.yml
  sudo: yes
- include: build.yml
  sudo: yes
- include: deploy.yml
  sudo: yes
