---
- include: yum.yml
  become: true
  tags:
    - repox_yum
- include: ssl-selfsign.yml
  become: true
  tags:
    - repox_ssl
- include: services.yml
  become: true
  tags:
    - repox_services
- include: database.yml
  become: true
  tags:
    - repox_database
- include: source.yml
  become: true
  tags:
    - repox_source
- include: build.yml
  become: true
  tags:
    - repox_build
- include: deploy.yml
  become: true
  tags:
    - repox_deploy
- include: proxy.yml
  become: true
  tags:
    - repox_proxy

