---
- name: Copy 00repox_vhost.conf into /etc/httpd/conf.d/
  template:
    src: 00repox_vhost.conf.j2
    dest: /etc/httpd/conf.d/00repox_vhost.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
- name: Restart httpd.service
  service:
    name: httpd
    state: restarted
- name: Add Admin User to Proxy Password File
  htpasswd: 
    path: /etc/httpd/proxypass
    name: admin
    password: admin
    owner: apache
    group: apache 
    mode: 0640
